# ── Configuration ─────────────────────────────────────────────────────────────
SHELL      := /usr/bin/env bash
BASE_IMAGE ?= debian:trixie-slim

# Detect container runtime: prefer Podman, fall back to Docker
CONTAINER_RUNTIME := $(shell command -v podman 2>/dev/null || command -v docker 2>/dev/null)
export DOCKER_HOST ?= unix:///run/user/$(shell id -u)/podman/podman.sock

# ── CI-safe scenario lists per feature ────────────────────────────────────────
# 'full' and hardware-dependent scenarios are excluded here.
# Run them locally with: make test-all FEATURE=vtune
SCENARIOS_vtune := vtune_pinned_version
# SCENARIOS_my-other-feature := scenario1 scenario2

# ── Help ──────────────────────────────────────────────────────────────────────
.PHONY: help
help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) \
	  | awk 'BEGIN {FS = ":.*##"}; {printf "  \033[36m%-35s\033[0m %s\n", $$1, $$2}'

# ── Pull base image ───────────────────────────────────────────────────────────
.PHONY: pull-base
pull-base: ## Pull and cache the base image. Override: make pull-base BASE_IMAGE=ubuntu:24.04
	@echo "==> Pulling $(BASE_IMAGE)..."
	$(CONTAINER_RUNTIME) pull $(BASE_IMAGE)

# ── Clean ─────────────────────────────────────────────────────────────────────
.PHONY: clean
clean: ## Remove dangling container images left by test runs
	@echo "==> Cleaning up dangling images..."
	$(CONTAINER_RUNTIME) image prune -f

# ── Guards ────────────────────────────────────────────────────────────────────
.PHONY: _require-feature
_require-feature:
	@test -n "$(FEATURE)" \
	  || { echo "ERROR: FEATURE is not set. Usage: make <target> FEATURE=vtune"; exit 1; }

.PHONY: _require-scenario
_require-scenario:
	@test -n "$(SCENARIO)" \
	  || { echo "ERROR: SCENARIO is not set. Usage: make test FEATURE=vtune SCENARIO=vtune_pinned_version"; exit 1; }

# ── lint-all ──────────────────────────────────────────────────────────────────
.PHONY: lint-all
lint-all: ## Lint all features at once
	@echo "==> Linting shell scripts in src/ and test/ ..."
	@find src test -type f -name "*.sh" -print0 \
	  | xargs -0 -r shellcheck
	@echo "==> All lint passed."

# ── Generic targets ───────────────────────────────────────────────────────────
# All targets below require FEATURE to be set.
# Usage:
#   make lint        FEATURE=vtune
#   make test        FEATURE=vtune SCENARIO=vtune_pinned_version
#   make test-all    FEATURE=vtune   (all scenarios from SCENARIOS_<feature>)
#   make test-full   FEATURE=vtune   (all scenarios including hardware-dependent)
#   make test-images FEATURE=vtune

.PHONY: lint
lint: _require-feature ## Lint a feature. Usage: make lint FEATURE=vtune
	@echo "==> Linting src/$(FEATURE)/*.sh and test/$(FEATURE)/*.sh ..."
		@find src/$(FEATURE)/ src/$(FEATURE)/ -type f -name "*.sh" -print0 \
	  | xargs -0 -r shellcheck
	@echo "==> Lint passed."

.PHONY: test
test: _require-feature _require-scenario lint ## Run a single scenario. Usage: make test FEATURE=vtune SCENARIO=vtune_pinned_version
	@echo "==> [$(FEATURE)] scenario: $(SCENARIO)"
	devcontainer features test \
	  -f $(FEATURE) \
	  -i $(BASE_IMAGE) \
	  --filter $(SCENARIO)

.PHONY: test-all
test-all: _require-feature lint ## Run all CI-safe scenarios for a feature. Usage: make test-all FEATURE=vtune
	@echo "==> Testign all scenario for feature [$(FEATURE)]"
	devcontainer features test \
	  -f $(FEATURE) \
	  -i $(BASE_IMAGE) \
	  --skip-autogenerated
	@echo "==> [$(FEATURE)] all CI-safe scenarios passed."

.PHONY: test-images
test-images: _require-feature lint ## Test a feature across multiple base images. Usage: make test-images FEATURE=vtune
	@for image in debian:trixie-slim debian:bookworm-slim ubuntu:24.04 ubuntu:26.04; do \
	  echo "==> [$(FEATURE)] testing on ${image}..."; \
	  $(MAKE) test-all FEATURE=$(FEATURE) BASE_IMAGE=${image} || exit 1; \
	done